Feat 그림판 도형 객체 생성 16
42-PINTING/FE-PINTING pull request #25
Opened 2024-05-31 10:52 UTC by mantoing

## 연관된 이슈
- Closes #16 

## 작업 내용
- penTool 기능정리
- 삼각형, 사각형, 원 버튼도구 추가
- canvas 노드모듈 오류 해결
- Makefile 수정
## 작업 브랜치 이름
`Closes #16 `

## 리뷰 요구사항 (선택)

2024-06-01 03:56 UTC, contemplation-person requested changes
깃허브 액션 해결 하고 두개 정도만 답변해줘 :)

2024-06-01 03:56 UTC, contemplation-person commented on src/app/painting/_component/_utils/shapeTool.tsx
> +};
mouse down, move, up의 차이가 뭔지 모르겠어 조금 알아볼 수 있도록 함수 이름을 바꿔줘

2024-06-01 03:56 UTC, contemplation-person commented on src/app/painting/_component/_utils/penTool.tsx
> +export const basicPen = (canvas: any) => {
no any type!

2024-06-01 20:19 UTC, mantoing commented on src/app/painting/_component/_utils/shapeTool.tsx
> +};
어 다운은 마우스를 누를때 움직일때는 누르고 드래그할때 업은 땔때인데 캔버스 옵션에따라서 함수명을 적은거라 바꾸는게 더 어려울거같아요

2024-06-01 21:29 UTC, contemplation-person commented on src/app/painting/_component/_utils/shapeTool.tsx
> +};
그렇다면 주석이라도 써주면 좋을 것 같아 :)

2024-06-01 21:34 UTC, contemplation-person commented
지금 액션 고친 것 같은데, 설명이나 레퍼런스  부탁해 :)

액션 고치면 도커 컴포즈에서 빌드하거나 환경설정 할 때마다 다 고쳐야해서 명확하게 모르고 고치면 나중에 난감할 수 있거든

2024-06-02 03:22 UTC, contemplation-person requested changes

2024-06-02 03:22 UTC, contemplation-person commented on .github/workflows/main.yml
> +          sudo apt-get update && sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
지금 액션 고친 것 같은데, 설명이나 레퍼런스  부탁해 :)

액션 고치면 도커 컴포즈에서 빌드하거나 환경설정 할 때마다 다 고쳐야해서 명확하게 모르고 고치면 나중에 난감할 수 있거든

2024-06-08 15:54 UTC, merged