Feat/febric.js로기초적인그림판구현#1
42-PINTING/FE-PINTING pull request #5
Opened 2024-04-16 09:19 UTC by mantoing

기초적인 그림판 기능 구현하였습니다.

2024-04-17 03:30 UTC, contemplation-person reviewed
훅으로 빼서 whiteBoard 함수를 깔끔하게 만드는 것에 대한 의견

2024-04-17 03:30 UTC, contemplation-person commented on src/app/painting/_component/whiteBoard.tsx
> +  };
요만큼을 훅 같은 것으로 빼는 건 어때?
도구 요소가 많아지면 함수가 길어질 것 같은데?

2024-04-18 07:59 UTC, mantoing commented on src/app/painting/_component/whiteBoard.tsx
> +  };
아 일단 이걸 디폴트로 가져가는게 아니라 헷갈려가지고 일단 지금까지 진행상황을 머지하고 되돌리기 이런거 추가할때 훅으로 분리하려고 합니다

2024-05-13 14:36 UTC, contemplation-person requested changes

2024-05-13 14:36 UTC, contemplation-person commented on .DS_Store
지워주고, gitignore에 등록해줘

2024-05-13 14:36 UTC, contemplation-person commented on src/app/layout.tsx
>      <html lang='en'>
```suggestion
    <html lang='ko'>
```

2024-05-13 14:36 UTC, contemplation-person commented on src/app/painting/_component/whiteBoard.tsx
> +        height='600'
나중에 그림판 비율로 크기 정할 거지?

2024-05-13 14:36 UTC, contemplation-person commented on src/app/painting/_utils/penPanningTool.tsx
> +    const e = opt.e;
e? event?

2024-05-13 14:36 UTC, contemplation-person commented on src/common/utils/recoilProvider.tsx
> +  return <RecoilRoot>{children}</RecoilRoot>;
이거 꼭 recoilroot provider에서 제공해야하는 거야? layout에서 바로 제공하면 안되니?

2024-05-13 14:41 UTC, contemplation-person requested changes
이거 빌드가 안되어 머지도 안된다 해결해줘 :)

2024-05-18 06:34 UTC, mantoing commented on src/app/painting/_component/whiteBoard.tsx
> +        height='600'
네 아직 레이아웃이 나오지 않아서 확인하고 변경해야 할것 같아요

2024-05-18 06:34 UTC, mantoing commented on src/app/painting/_utils/penPanningTool.tsx
> +    const e = opt.e;
event용

2024-05-18 06:36 UTC, mantoing commented on src/common/utils/recoilProvider.tsx
> +  return <RecoilRoot>{children}</RecoilRoot>;
네 이게 페이지 컴포넌트일때는 layout도 가능하다는데 일단 기본 사용법은 따로 프로바이더 제공하는게 오류 발생이없다고 하더라구요

2024-05-18 07:44 UTC, contemplation-person commented on src/app/layout.tsx
> -}: Readonly<{
Readonly 왜 빠졌니?

2024-05-18 08:11 UTC, merged