79 feat 텍스트 삽입 할수있게 기능구현
42-PINTING/FE-PINTING pull request #80
Opened 2024-07-05 07:53 UTC by mantoing

## 연관된 이슈
- #79 

## 작업 내용
- 텍스트 입력영역 지정기능을 구현하였습니다.

## 작업 브랜치 이름
`79/feat 텍스트 삽입 할수있게 기능구현`

## 리뷰 요구사항 (선택)

2024-07-06 16:00 UTC, contemplation-person requested changes
확인 부탁함.

2024-07-06 16:00 UTC, contemplation-person commented on src/app/painting/_component/_utils/textTool.tsx
> +    });
if 문을 지워버리고 아래처럼 적으면 더 예쁘지 않을까 생각함 
`   
rect.set({
      width: Math.abs(origX - pointer.x),
      height: Math.abs(origY - pointer.y),
      left : Math.min(origX, pointer.X),
      top : Math.min(origY, pointer.Y),
 });`
여도 같은 의미 같은데?

2024-07-06 16:00 UTC, contemplation-person commented on src/app/painting/_component/_utils/textTool.tsx
> +      }
이렇게 최소 크기를 체크하는 것보다 기본으로 값을 넣어주는게 좋을 것 같음.
단순히 클릭을 해도 10 * 10의 상자가 나타날 수 있도록.

2024-07-12 12:27 UTC, mantoing commented on src/app/painting/_component/_utils/textTool.tsx
> +      }
일단 클릭만으로 처리하게 하긴 했는데 문제는 텍스트 박스를 만들고 그안에 값을 집어넣으려고 클릭하려는 순간에 또 텍스트 박스가 생성되는 오류가 발생함. 논의해봐야 할거같음

2024-07-20 05:30 UTC, contemplation-person commented on src/app/painting/_component/_utils/textTool.tsx
> +      }
이 부분 수정 후 머지하는 것으로 하자 :)

2024-07-20 19:54 UTC, mantoing commented on src/app/painting/_component/_utils/textTool.tsx
> +      }
이해를 못하겠습니다. 고정된박스요 ??

2024-07-24 09:49 UTC, contemplation-person approved these changes

2024-07-25 03:04 UTC, merged